#!/bin/bash
echo Content-type: text/html
echo 
echo 

source  /var/www/rrdtool/scripts/config.sh
hostConf=host_config.list
######################
echo '
<html>
<head>
<title>
</title>
<style type="text/css">
table{width:40%;border:2px solid #ccc;border-width:1px;background:CAE5E8;}
</style>
</head>
<body ><center>
<br>
<H1 class="STYLE1">常规设置</H1>
<hr size="4" color="#CAE5E8">
<br>

</body>
</html>'
